var CreateForm = require('./lib/CreateForm');
var {createLambdaFunction, createLambdaBucket} = require('./lib/CreateLambda');
var UpdateLambdaFunction = require('./lib/UpdateLambda');
var CreateTemplate = require('./lib/CreateTemplate');
var ValidateTemplate = require('./lib/ValidateTemplate');
var CreateStack = require('./lib/CreateStack');
var UpdateStack = require('./lib/UpdateStack');
var DeleteStack = require('./lib/DeleteStack');
var GetApiUrl = require('./lib/GetApiUrl');
var Email = require('./lib/SesEmail');
var GetSubmissions = require('./lib/GetSubmissions')
var ExportSubmissions = require('./lib/ExportSubmissions')
var FormConfig = require('./lib/Config')
var {initBuild} = require('./build')
var InitForm = require('./lib/InitForm')
var Iam = require('./lib/CreateIamUser')

module.exports.GetSubmissions = GetSubmissions;
module.exports.ExportSubmissions = ExportSubmissions;
module.exports.CreateForm = CreateForm;
module.exports.CreateLambdaFunction = createLambdaFunction;
module.exports.CreateLambdaBucket = createLambdaBucket;
module.exports.UpdateLambdaFunction = UpdateLambdaFunction;
module.exports.CreateTemplate = CreateTemplate;
module.exports.ValidateTemplate = ValidateTemplate;
module.exports.CreateStack = CreateStack;
module.exports.UpdateStack = UpdateStack;
module.exports.DeleteStack = DeleteStack;
module.exports.GetApiUrl = GetApiUrl;
module.exports.VerifyDefaultEmail = Email.VerifyDefaultEmail;
module.exports.SesEmail = Email.SesEmail;
module.exports.VerifySesEmail = Email.VerifySesEmail;
module.exports.ValidateSesEmail = Email.ValidateSesEmail;
module.exports.CreateIamUser = Iam.CreateIamUser;
//module.exports.UpdateAwsProfile = Iam.AddAwsProfile;
//module.exports.UpdateAwsRegion = Iam.AddAwsRegion;
module.exports.ParseFields = FormConfig.ParseFields;
module.exports.AddConfigVariable = FormConfig.AddVar;
module.exports.Build = initBuild;
module.exports.InitForm = InitForm;
module.exports.CreateLabel = FormConfig.CreateLabel;
module.exports.FormSetup = FormConfig.CheckForm;